# Generated by Django 2.1.4 on 2018-12-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181215_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='launched_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
