# Generated by Django 2.1.4 on 2019-02-02 05:06

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_carpost_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='company_name',
            field=django_bleach.models.BleachField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carpost',
            name='model_name',
            field=django_bleach.models.BleachField(max_length=40),
        ),
    ]
