# Generated by Django 2.1.4 on 2019-02-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190202_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='company_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carpost',
            name='model_name',
            field=models.CharField(max_length=40),
        ),
    ]
