# Generated by Django 2.1.4 on 2018-12-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181217_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carpost_pics/'),
        ),
    ]
