# Generated by Django 2.1.4 on 2019-02-02 06:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190202_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpost',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
