# Generated by Django 2.1.4 on 2019-02-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_carpost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpost',
            name='company_contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
