# Generated by Django 2.1.4 on 2019-02-02 06:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_carpost_company_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
