# Generated by Django 2.1.4 on 2019-02-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190202_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='company_name',
            field=models.TextField(max_length=50),
        ),
    ]
