# Generated by Django 2.1.4 on 2019-02-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190204_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='company_name',
            field=models.CharField(max_length=50),
        ),
    ]
