# Generated by Django 2.1.4 on 2019-02-03 23:44

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190204_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='company_name',
            field=django_bleach.models.BleachField(),
        ),
        migrations.AlterField(
            model_name='carpost',
            name='model_name',
            field=django_bleach.models.BleachField(),
        ),
    ]
