# Generated by Django 2.1.4 on 2019-04-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190204_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='launched_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
